connP_path = 'C:\Users\user\Desktop\jeng\2022CerebellumPrj\code\conn_33subject_physio(addTO39subject)';
connP_filename = 'conn_project01';
roifilepath = 'C:\Users\user\Desktop\jeng\2022CerebellumPrj\code\ROI';
roifilename = string(ls(fullfile(roifilepath,'*.nii')));
roiname = split(roifilename,'.');

for nfile = 1:length(roifilename)
conn_batch('filename',fullfile(connP_path,[connP_filename,'.mat']),...
    'Setup.rois.add',1, ...
    'Setup.rois.files',{[fullfile(roifilepath,char(roifilename(nfile)))]}, ...
    'Setup.rois.names',{roiname(nfile)}, ...
    'Setup.done',1,...
    'Setup.overwrite',0,...
    'Denoising.overwrite',0,...
    'Denoising.done',1,...
    'Analysis.Source',{roiname(nfile)}, ...
    'Analysis.overwrite',0,...
    'Analysis.done',1);
end